version: '3.9'
services: 
  backend:
    container_name: contacts_api
    build: ./
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - HOSTNAME=db
      - DB_NAME=contacts_api
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"] 
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: contactsdb
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
