name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run : npm test     

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
      - name: Install dependencies
        run: |
          npm install
          npm run test
          

